CREATE TABLE "systems" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "planets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "system_id" int
);

CREATE TABLE "resources" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar
);

CREATE TABLE "planet_resources" (
  "planet_id" int,
  "resource_id" int,
  "primary" key(planet_id,resource_id)
);

ALTER TABLE "planets" ADD FOREIGN KEY ("system_id") REFERENCES "systems" ("id");

ALTER TABLE "planet_resources" ADD FOREIGN KEY ("planet_id") REFERENCES "planets" ("id");

ALTER TABLE "planet_resources" ADD FOREIGN KEY ("resource_id") REFERENCES "resources" ("id");
